num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
a = (num1 > num2)
b = (num1 < num2)
c = (num1 == num2)
print("First number is greater than second number ", a)
print("First number is less than second number ", b)
print("First number is equal to second number ", c)